### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by IzzySoft**
Just some minor adjustments which might be useful for others as well, so I thought I give something back. As I forked from you (and there's no recent activity further upstream), you get the PR (feel free to push it further up if you like). Additional improvements planned :)

### CODE REVIEW

**Comment by IzzySoft** [comment]
Just a little "ping": Are you not interested – or still checking? ;)

Btw: Script runs with PR'd modifications on multiple machines (Debian, Ubuntu; ARM (BananaPi) and x64), so I'd say my changes didn't break anything.

**Comment by tpapp** [comment]
Thanks for the PR. Sorry, I am super-busy now with a deadline, will look at it during the weekend.

**Comment by IzzySoft** [comment]
OK, no prob. Was just wondering as there was no reply at all :)

**Comment by tpapp** [comment]
Thanks, I merged. Sorry for the delay.

**Comment by IzzySoft** [comment]
Thanks for merging! And no worries, I know what "being busy" means :)

**Comment by IzzySoft** [comment]
PS: Taking a look at [the timeline](https://github.com/SebKuzminsky/rsync-push-backup/network), it seems your "uplink" picked up work again. I've already [opened an issue there](https://github.com/SebKuzminsky/rsync-push-backup/issues/7) to see if we can put things together (basically, Seb duplicated my work but then went ahead).

Well, looking at [the timeline here](https://github.com/tpapp/rsync-push-backup/network) it seems Seb forked from you, so maybe he can just "pull in" the differences (I've already suggested him to cherry-pick). Would be a pity to leave a mess otherwise – and I don't want to reinvent the wheel Seb already has :)

**Comment by tpapp** [comment]
Yes, merging everything would be great. However, if the upstream author @mikaellanger has no time for this project, it would be fine with me if either you or Seb wanted to pick up this project. Originally, I only forked to contribute.

**Comment by IzzySoft** [comment]
I guess so did we all. Unfortunately, Seb forked a year ago and forgot to check the state of other forks before he finally began to work at his fork this year (actually unknowingly replicating some of my work). As he did the most of the work (his implementations go ahead of mine – what I planned to do next he's already done), I'd suggest him to pick up the diffs and become the "new master"). I've linked to my issue there from here, so he should see that and might chime in here. I surely hope he will :)

**Comment by SebKuzminsky** [comment]
Hi @IzzySoft & @tpapp, thanks for starting this conversation, it'd be better if we all worked together on this little project.  I don't feel any particular ownership over this project.  I actively use my fork of it to back up a couple of machines i manage, and I'd be happy to 'take point' on the combined project if no one else wants to, but i'd also be totally content to be a humble contributor if someone else wants to run it.

I think the github timeline graph gets a little confused about forks.  If you look at @mikaellanger's repo network it shows everything clearly:  https://github.com/mikaellanger/rsync-push-backup/network

I forked @mikaellanger's project a few weeks ago (in mid April 2016), but yeah i forgot to check his repo network for any recent work.  I would have based my work off one of your repos if i'd had my act together.

Looking at all our commit histories, the following things come to mind:

1. The max_size thing and the log/errlog thing will be easy to combine with my fork.
1. We should pick one of the "disable notifications" implementations.  I prefer how my implementation doesn't require a default setting in the backup script, but instead relies on bash's unset variable behavior for the default.  I also prefer my config variable name, but not strongly.
1. I appreciate @IzzySoft's work on the docs, though I think the project is small enough that splitting it into two files is not needed.  I also have done a little work on the docs, this would have to be merged manually.
1. There's a bunch of new stuff in my repo (ssh_id authentication, multiple "modules", support for multiple config dirs, tweaks to how the snapshot dirs are managed).  I implemented these because they're useful to me, though they do require some updates to existing configs so any existing users would have to be careful when beginning to use this code.

I've been trying to record issues I run into in my issue tracker: https://github.com/SebKuzminsky/rsync-push-backup/issues

**Comment by IzzySoft** [comment]
> 1 The max_size thing and the log/errlog thing will be easy to combine with my fork.

Yupp, the first definitively: You didn't work on the same feature, and I've just picked it from Tamas (and didn't touch it, except for adding a comment to the config).

> 2 We should pick one of the "disable notifications" implementations. I prefer how my implementation doesn't require a default setting in the backup script, but instead relies on bash's unset variable behavior for the default. I also prefer my config variable name, but not strongly.

No problems with me. Note that my implementation doesn't rely on a config setting either: I define a default before sourcing the config :) I'm also fine with your variable name (on my end, just 2 configs where I'll have to update it then).

> 3 docs

Though it's small, IMHO the `README.[md|txt]` on the "project main page" should focus on what the tool does, and leave details in a separate file. If more features are added in the future, we wouldn't need to "blow" it then :) But that's just my opinion (I value good documentation high, so I was planning to extend that at a later time).

> 4 There's a bunch of new stuff in my repo […]

Most of that was on my Todo list – so I welcome you've already implemented it. As the project was "silent" for quite a while, I don't think too many users will be affected anyway.

As for Mikael (the original project creator), according to his stats he seems to be inactive for a year at least. Good idea to contact him of course, but I'm not sure whether we can expect a response (or if he'd be willing to accept all our work as PR ad cherry-pick everything ;)

As for bragr: it looks like he mainly *removed* stuff (like the hourly code) to adjust it to his needs. I'd prefer not to pick that part; if hourly stuff is not wanted, it should better be *disabled* (i.e. deal with the case the corresponding variables indicate "0 snapshots") than removed. But we might consider the "code consolidation" he did.

**Comment by SebKuzminsky** [comment]
> As for bragr: it looks like he mainly removed stuff (like the hourly code) to adjust it to his needs. I'd prefer not to pick that part; if hourly stuff is not wanted, it should better be disabled (i.e. deal with the case the corresponding variables indicate "0 snapshots") than removed. But we might consider the "code consolidation" he did.

Agreed, @bragr's removal of hourly snapshots is a local customization that's not widely applicable.  The "consolidation" is similar to my commit SebKuzminsky/rsync-push-backup@f44f436b3a.  I'd be content ignoring that fork and focusing on merging the @tpapp, @IzzySoft, and @SebKuzminsky forks.

So....  Which one of us will take the lead on this?

**Comment by SebKuzminsky** [comment]
> > 3 docs

> Though it's small, IMHO the README.[md|txt] on the "project main page" should focus on what the tool does, and leave details in a separate file.

Thanks for explaining the reasoning for the split docs, I accept your opinion on this.

**Comment by IzzySoft** [comment]
> So.... Which one of us will take the lead on this?

I'd say you, as (of the 3 of us) you did the most work so far. Can you cherry-pick the relevant commits from @tpapp (his repo includes my commits as per this merge anyway – and I always try to keep commits "atomar", so it shouldn't be a big issue for most of them)?

I guess it would be a good idea then that I delete my fork (all my changes are already merged) and create a fresh one off your repo once you've integrated everything. I'd go over the documentation again then to have it reflect the new "status quo" – and offer my updates as PR, of course. Would you two agree with that?

As for documentation: In addition to bringing it up-to-date, I was thinking of having a "minimal config" in the corresponding directory, and a "full config" (with all the gimmicks) in the `doc/` directory then. That would help new users to a "quick start", and still allow to setup a more sophisticated installation easily (one of my reasons to have the `doc/` directory). Does that meet your approval?

**Comment by SebKuzminsky** [comment]
> I'd say you, as (of the 3 of us) you did the most work so far. Can you cherry-pick the relevant commits from @tpapp (his repo includes my commits as per this merge anyway – and I always try to keep commits "atomar", so it shouldn't be a big issue for most of them)?

That sounds fine to me.  I'll cherry-pick the easy commits out of @tpapp's repo into mine, and I'll ask for help (in the form of Issues in my repo) with the things that aren't immediately obvious to me (probably docs, and I dont know what else).

The .backup dir in my fork has a complete config, with comments.  My intention was that it'd be enough for anyone to customize their local config from that.  I think the config is still simple enough that there's no need to split it any further.  Just my opinion.

**Comment by SebKuzminsky** [comment]
I cherry-picked three commits from @tpapp's repo into mine:

1. Added an option for maximum size.
2. adding max_size example to config
3. separating log messages between STDOUT (normal) and STDERR (errors)

I modified 2 to fit in with my commented example config, and i modified 3 to work with multiple arguments.

I left the x_notify commit and the ssh pseudo-terminal behind since there's already similar commits in my fork.

I also didn't cherrypick the documentation commit; @IzzySoft will you redo that commit with my updated Readme and make a PR against SebKuzminsky/rsync-push-backup for it?

I propose we stop using this old PR for further project discussion and instead use new Issues & PRs in my repo.

**Comment by bragr** [comment]
@SebKuzminsky I haven't used my version in while so I haven't updated it much. If there is anything useful in my fork, feel free to reuse it. If not, no skin off my nose.

**Comment by SebKuzminsky** [comment]
Thanks @bragr, @IzzySoft and I looked through it and both came to the conclusion that the commits are of the "local customization" variety and not appropriate for our combined work.  But thanks for checking in with us!

**Comment by IzzySoft** [comment]
Cool, @SebKuzminsky – didn't expect it that fast! Today it's bed-time (1am here), but I'll see that I asap fork your repo, clone it, and check what to do on the docs. Give me a little time for that, as before I start on the docs I want to make sure the code still works with my setup  here :)

Confirmed on the x_notify and pseudo_tty stuff (saw you already have that). Also confirm to switch to separate issues from here on.

Also thanks @bragr for chiming in! Be welcome to participate anytime :)

**Comment by SebKuzminsky** [comment]
> before I start on the docs I want to make sure the code still works with my setup here :)

Smart.  The main incompatibility with @mikaellanger's repo is that the backup_root variable has moved from .backup/config to .backup/MODULE/config, and the exclude file has moved from .backup/ to .backup/MODULE.  Everything else should work unchanged.

If you run "bin/backup", it'll back up all modules.  You can also back up individual modules by naming them on the command line like "bin/backup MOD1 MOD2..."

Sleep well :-)

**Comment by IzzySoft** [comment]
Thanks! So what if (as with the original) there's no module defined at all – but just the global config? Or the global config and a global exclude? Well, I'll find out :)

**Comment by tpapp** [comment]
@SebKuzminsky: thanks for moving so quickly. I would be happy if you took over, my knowledge of Bash is shaky and any minor coding involves furious googling. I have forked the repo out of necessity to make a minor modification, but now that you have merged I will delete mine. I will continue the discussion in the issues there.

@IzzySoft: thanks for initiating this.

**Comment by IzzySoft** [comment]
@tpapp You're very welcome! Thought it was the best for all involved :) And even if your Bash is shaky, you can profit from it this way :)

@SebKuzminsky Initial fork done as well as initial commits (pushed to my fork). If you agree with my changes, I'll make a PR and we switch over :)

**Pull request merged**
